import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import {CssBaseline} from "@mui/material";
import * as React from 'react';

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body>
      <AppRouterCacheProvider>
        <CssBaseline/>
        {children}
      </AppRouterCacheProvider>
      </body>
      </html>
  );
}
